# Generated by Django 4.2.5 on 2023-09-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cmc', models.IntegerField()),
                ('colorIdentity', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cardId', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.ManyToManyField(to='main_app.card')),
            ],
        ),
    ]
